### ISSUE TITLE
Bevinding / Tools: Handige tool bij het ontwikkelen voor multi-device websites

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#1]
Aangezien wij niet zeker weten wat Vasilis' testapparaat zal zijn, leek het mij handig om het volgende er weer bij te halen. Voor de mensen die geen Front End 1 gevolgd hebben, hierbij een tool die voor jou browser eigenschappen kan detecteren. Hierbij kan je bijvoorbeeld voor Touch-devices grotere knoppen aanmaken (vanwege de "Fat fingers-principle"), kijken of de browser _nieuwe_ CSS3 elementen begrijpt en noem maar op. Op basis van deze informatie kan je dus een fallback creēren, zodat de browsers die niet de nieuwste van het nieuwste CSS3-feature pakt toch er goed uit kan zien.

Hierbij:
http://modernizr.com

Succes!

<Vragen over Modernizr kan hier gepost worden :'3>

**Comment by IAmABear** [comment]
Een andere leuk tool om te kijken hoe de website reageert op verschillende devices is:
http://quirktools.com/screenfly/

Hoewel hij op sommige punten vaag werkt (als je frankwatching invult link hij door b.v.) krijg je toch bij veel websites er handige informatie uit.

**Comment by HiddeStatema** [comment]
Nog een handige tool! Mac only.
https://itunes.apple.com/nl/app/duo/id777886035?mt=12

**Comment by vasilisvg** [comment]
Nog een [voor het kiezen van de juiste HTML](http://html5doctor.com/downloads/h5d-sectioning-flowchart.png)

**Comment by alisahin** [comment]
Hierbij een overzicht van html5 elementen die je kan gebruiken voor je website.
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/HTML5_element_list

**Comment by MartijnEngelkes** [comment]
http://www.responsinator.com 

Werkt ook erg goed, vul bovenaan de link van je website in en je kunt bekijken hoe het er uit ziet op veel verschillende devices.

**Comment by JanJurre** [comment]
Ik kwam Foundation (http://foundation.zurb.com/) en Gridless (http://thatcoolguy.github.io/gridless-boilerplate/) tegen. Beide Mobile-first/responsive hulpmiddelen.
Nog niet uitgebreid geprobeerd, maar lijkt er goed uit te zien.

**Comment by KoopReynders** [comment]
All the problems we have with websites are ones we create ourselves.
This site doesn't care if you're on an iMac or a motherfucking Tamagotchi.
http://motherfuckingwebsite.com
