### ISSUE TITLE
position: fixed!?!

### ISSUE THREAD

**Issue by rappel93** [CMDA/mi-mobile-design-forum#101]
Hallo,

Ik heb mij menubalk een position:fixed meegegeven. Dat werkt allemaal prima. Totdat hij bij de context aankomt. Op de een of andere reden komt de context boven het menu te staan (te zien in onderstaande afbeelding) Weet iemand waarom dit is?
![knipsel](https://cloud.githubusercontent.com/assets/7491549/3306172/712b1cbc-f65e-11e3-909e-c8416855a6bf.JPG)

**Comment by JBostelaar** [comment]
Pas de z-index van je menubalk aan, zorg dat deze hoger is dan die van je context.

**Comment by TVoorend** [comment]
bijvoorbeeld: .menuclass { z-index:100;}
