### ISSUE TITLE
Section vs. Article vs. Div

### ISSUE THREAD

**Issue by ghost** [CMDA/mi-mobile-design-forum#12]
Voor de mensen die twijfelen hoe ze nu precies Article, Section en Div elementen het beste kunnen gebruiken, check:

http://www.w3schools.com/html/html5_semantic_elements.asp
http://oli.jp/2009/html5-structure1/
http://www.my-html-codes.com/html5-article-or-section-tag

Quote uit de laatste link:
“Think of a newspaper. The paper comes in sections. You have the sports section, real estate section, maybe home & garden section etc. Each of those sections in turn has articles in it. And some of those articles are divided into sections themselves."

**Comment by IAmABear** [comment]
Die quote maakt het serieus zoveel duidelijker. Zat zelf ook eerst aardig te twijfelen wanneer wat te gebruiken maar toen ik dat las was het een stuk duidelijker, nu de uitvoering nog.
