### ISSUE TITLE
HTML5 Tags Index

### ISSUE THREAD

**Issue by ghost** [CMDA/mi-mobile-design-forum#13]
Overzicht van alle HTML5 tags, inclusief uitleg en voorbeelden:

http://html5doctor.com/

Graag gedaan.

**Comment by rappel93** [comment]
Hoe zit het tegenwoordig met de ondersteuning van al deze html5 tags? Tijdens front end 1 was dit namelijk nog wel een gedoe om het overal werktend te krijgen....
