### ISSUE TITLE
HTML5 stylesheet reset

### ISSUE THREAD

**Issue by ghost** [CMDA/mi-mobile-design-forum#15]
Aangezien we niet zeker weten op welk apparaat Vasilis onze websites gaat testen leek het mij handig om dit te implementeren:

http://html5doctor.com/html-5-reset-stylesheet/

Deze 'reset sheet' is speciaal voor HTML5, er staat ook een linkje naar de algemene reset stylesheet (altijd handig!). Verder staat er uitgelegd wat er allemaal is aangepast, wat het doet en <strong>waarom </strong>.

**Comment by Barry91** [comment]
Let op dat je eerst de reset stylesheet in laad en daarna pas de custom (eigen) stylesheet!
