### ISSUE TITLE
<Bevinding> Typografie: A few simple rules;

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#18]
Typografie stond deze week centraal en bij het toepassen daarvan op jouw webdesign komen heel wat dingen kijken. Op het moment ben ik een aantal artikelen aan het lezen dat handig kan zijn bij het kiezen/vormgeven van jouw typografie. 

De artikelen:
- http://ia.net/blog/100e2r
- http://markboulton.co.uk/journal/five-simple-steps-to-better-typography

Zodra ik er meer vind zal ik ze hier posten!

**Comment by MartijnEngelkes** [comment]
Hier nog een interessant stuk dat nog recent is geschreven waar ook in wordt gegaan of mobiele devices:

http://www.emerce.nl/best-practice/lettertypes-leesbaarheid-meer-conversies

**Comment by sjoerdvalk1991** [comment]
Nuttige stukjes over typography

http://elliotjaystocks.com/blog/responsive-web-typography

http://css-tricks.com/viewport-sized-typography/

En een video (nog niet gekeken)

http://vimeo.com/m/74368443
