### ISSUE TITLE
Bevinding / Tools: Slimmer en sneller coden

### ISSUE THREAD

**Issue by bramswier** [CMDA/mi-mobile-design-forum#2]
Omdat we vanaf de basis onze website gaan opbouwen (en voorlopig nog geen gebruik maken van frameworks), zal elk HTML- (deze week) en CSS-element met de hand moeten worden ingevoerd. Er zijn tools die dit proces vergemakkelijken. Een daarvan is Emmet voor Sublime Text. Als je bijvoorbeeld een ul-element met drie li-elementen wil, kan dit als volgt:

![multiplication](https://cloud.githubusercontent.com/assets/3028474/2748361/bf85cf6c-c7bd-11e3-9208-bdbbadeabb5d.gif)

Hier een uitgebreid artikel over de mogelijkheden: http://www.smashingmagazine.com/2013/03/26/goodbye-zen-coding-hello-emmet-2/

**Comment by TDMW** [comment]
Wil dit komende week gaan proberen: http://csshat.com/?utm_source=photoshopkiller_com&utm_medium=website&utm_campaign=photoshopkiller

Nog geen tijd voor gehad, maar lijkt me (mits het werkt) erg handig. De tip om http://css3ps.com/ te gebruiken heb ik ook gehad, dus beide sowieso even proberen.

**Comment by TVoorend** [comment]
Emmet is een goede plugin! Zeker een aanrader!

**Comment by arjentnkmp** [comment]
Thank Bram, ik kende deze nog niet! :-D
