### ISSUE TITLE
Question / Image resizing

### ISSUE THREAD

**Issue by IAmABear** [CMDA/mi-mobile-design-forum#20]
Afgelopen dagen veel bezig geweest met verschillende plaatjes afbeelden op verschillende browsers / mobile apparaten. Ik blijf echter met bepaalde issues zitten. Indien ik een afbeelding zijn hoogte op 20% zet b.v. komt dit op de browser goed uit, echter bij mobile apparaten zoals iPhone 5 is het plaatje ineens het hele scherm. Heeft iemand enige idee hoe ik er voor zorg dat de afbeelding 20% van de mobiel zijn scherm neem zonder allemaal media queries te doen? Ik heb overigens in de meta viewport width=device-width en initial-scale = 1 of random scaling tegens te gaan.

P.S. het probleem doet zich voornamelijk voor wanneer ik de breedte van de plaatjes op 100% zet. Bij kleinere breedtes schaalt hij wel naar behoren tot nu toe (of ik zie het gewoon niet bij kleinere afbeeldingen).

Iemand suggesties of oplossingen?

**Comment by Barry91** [comment]
Zou je de pagina online kunnen zetten, zodat we er naar kunnen kijken? Ik denk dat het probleem op die manier veel makkelijker te identificeren is. Je zou de properties max-height/max-width kunnen proberen.

**Comment by IAmABear** [comment]
Hier is een van de pagina ( de gene waar ik de meeste shit aan het op zetten ben atm ). http://dev.floydvanboksel.com/hva/designformobile/portfolio.html

**Comment by sjoerdvalk1991** [comment]
Ik denk dat je toch met media queries moet gaan werken. De onderste afbeelding ziet er nu op portrait modus prima uit op iphone 5, maar op landscape wordt deze helemaal uitgerekt.

**Comment by rizkicalame** [comment]
Wat Sjoerd zei. Met behulp van Media Queries kan je heel _simpel_ in jouw CSS alternatieve stijlregels toepassen, bijvoorbeeld wanneer jouw website op een mobieltje bekeken wordt. Als je wilt, kan je me even PMen op Facebook, dan leg ik je alle fijne details erover uit. :-)

**Comment by arjentnkmp** [comment]
Jep, Media Queries doen de truuk. Als je gebruik zou maken van een CMS als Wordpress (dus niet specifiek voor deze opdracht, maar meer algemeen) kun je ook de geuploade afbeeldingen automatisch laten resizen naar een vooraf ingesteld formaat (functions.php). Ik gebruik dit vaak, en roep dan een ander formaat afbeelding op (zodat de kwaliteit goed blijft, niet alle browsers schalen zonder al te veel kwaliteitsverlies).

**Comment by IAmABear** [comment]
Oke, dan word het toch maar media queries. Probeerde hier juist weg van te blijven om een algemene stylesheet te bouwen zonder 10 duizend uitzonderingen. Met wordpress ben ik bekend en dat werkt meestal naar behoren. Anyhow tnx voor de antwoorden ^^
