### ISSUE TITLE
Bevinding / Cross browser check

### ISSUE THREAD

**Issue by martijnroosenhart** [CMDA/mi-mobile-design-forum#22]
Misschien is het een handige tool als je wil weten hoe jou website er in een andere browser eruit ziet. Je kan deze live testen als je een gratis account aanmaakt. 

http://www.browserstack.com

**Comment by TDMW** [comment]
Deze website kende ik nog niet, echter kwam ik deze ooit ook zelf tegen. Hier kun je ook een OS kiezen (geen idee of dat browserstack ook kan): https://crossbrowsertesting.com/

Nog nooit zelf gebruik van gemaakt, misschien snel maar eens doen.

**Comment by arjentnkmp** [comment]
Voor het testen van je website in Internet Explorer zijn een heleboel tools beschikbaar, zelf werk ik het liefst met een virtual machine (op OSX, of op Windows om oudere browsers te testen) omdat dat veel directer is dan browsershots.

Hier: http://www.modern.ie/en-us

Kun je gratis diverse virtual machines downloaden voor IE. Ze werken allemaal met VirtualBox (en andere programma's). VirtualBox is gratis te verkrijgen.

**Comment by alisahin** [comment]
Daarnaast is het verstandig om altijd even te controleren of iets wordt ondersteunt door een browser. Dit kun je doen op: http://caniuse.com Op deze manier weet je meteen voor welke browsers je progressive enhancement moet toepassen. Uiteraard kun je het voor de zekerheid nog testen in de browser.

**Comment by TVoorend** [comment]
Ik gebruik ook vaak de website caniuse.com en browserstack.com, voordeel van browserstack is dat hij een browser namaakt en niet een screenshot ervan maakt. Dit houdt in dat je eigelijk een browser opent via de website, hierdoor is het mogelijk om dingen te inspecteren en kijken wat er mis gaat. bij screenshot is dit veel moeilijker om te achterhalen.
