### ISSUE TITLE
Question / nieuwssite / Voorkeuren voor fonts?

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#23]
Ik was net even aan het rondneuzen en schrok toch wel van het font dat www.rtlnieuws.nl gebruikt voor hun content. Is dit nou extreem goed leesbaar? Het is in ieder geval spuuglelijk.

Zijn er misschien mensen die fonts hebben gevonden die hiervoor beter van toepassing zijn.

**Comment by MilanDembinski** [comment]
Dat ziet er inderdaad niet best uit.. Ik vond dit tooltje (http://www.fontpicker.net), het helpt niet perse met wat een "goed" font is maar maakt het wel een stuk makkelijker om ze te vergelijken en een te kiezen.

**Comment by rizkicalame** [comment]
Ik denk dat je ook goed moet gaan kijken naar andere (online) nieuwssites. Je ziet duidelijk verschil tussen de titels, kopjes, subkopjes e.d. Ik zeg niet dat je het klakkeloos moet overnemen, maar je kunt wel gaan zoeken naar gelijksoortige fonts.

**Comment by rappel93** [comment]
Denk dat het bij deze site niet echt aan de fontkeuze ligt, maar meer aan de verschillende groottes. Hierdoor wordt het gelijk heel onoverzichtelijk en druk (voor mij dan.)

**Comment by arjentnkmp** [comment]
Ik moet eigenlijk zeggen dat ik het wel een mooi font vind, alleen of het geschikt is voor het lezen weet ik niet. Wat ik vaak hoor is dat er voor een headline font sans-serif gekozen moet worden, en voor de content serif. Dit is in ieder geval bij print vaak zo.

**Comment by alisahin** [comment]
Ik gebruik meestal Google fonts. Daar kun je filteren op schreef en schreefloze fonts.
Ik zou zeggen, kijk eens even rond. Zitten zeker goede fonts tussen. Op de website kun je lezen hoe je het allemaal implementeert in een website.
https://www.google.com/fonts

**Comment by JanJurre** [comment]
Ik vind het zelf geen vervelend font om te lezen. Helemaal prachtig is het niet, maar dat is ook niet hun primaire boodschap.

@ali Die googlefonts is erg handig. Ik zit zelf altijd te prutsen om het goed voor elkaar te krijgen, dat hoeft dus niet meer ;)

**Comment by HiddeStatema** [comment]
Toen ik de RLTNieuws pagina voor het eerst zag schrok ik! Misschien is het ook handig om te kijken naar Blendle (www.blendle.nl). Ik vind hun typografie wel lekker en rustig!

**Comment by vasilisvg** [comment]
Er is [een video verschenen](http://vimeo.com/94134581) over de designkeuzes voor de RTL nieuws site. Ik hoor volgende week graag van jullie allemaal waar hij over ging.

**Comment by vasilisvg** [comment]
En een [case study](http://john-beckers.squarespace.com/rtl-nieuws/), ook nog!
