### ISSUE TITLE
Dealing with images (heel veel links in de comments)

### ISSUE THREAD

**Issue by MartijnEngelkes** [CMDA/mi-mobile-design-forum#24]
Een interessant stuk wat ik las over het gebruik van afbeeldingen in je ontwerp. Ook enkele afbeeldingen van usability tests met een eye-tracker. Op welke plekken van je website is de gebruiker het meest gefocused?

http://www.1stwebdesigner.com/design/images-on-web-design-usability-guide/

**Comment by Bizberg** [comment]
Dit is echt een aanrader om te lezen, want hoewel het logisch lijkt, doen de meeste webdesigners dit nog steeds fout.

**Comment by vasilisvg** [comment]
Hier nog [een wat filosofisch verhaal](http://alistapart.com/column/look-at-the-big-picture) over hoe om te gaan met responsive images. Goed om even door te nemen!

**Comment by vasilisvg** [comment]
En hier nog een prachtig geillustreerd, gedetailleerd [technisch artikel over responsive images](http://ericportis.com/posts/2014/srcset-sizes/).

**Comment by MartijnEngelkes** [comment]
http://mashable.com/2013/10/29/image-compressors/

Voor degene die ook nog aan het kloten zijn om foto's flink te comprimeren. In deze link staan heel veel online tools waar je je foto's mee kunt optimaliseren voor het web.
