### ISSUE TITLE
Gezocht: Duo

### ISSUE THREAD

**Issue by oledi** [CMDA/mi-mobile-design-forum#26]
Tot deze week ging het allemaal nog wel in mijn eentje. Nu wil echter goed aan de bak gaan met het css deel en wil ik hier graag hulp van een coder bij. 
Is er iemand die nog een duo zoekt? Overigens doe ik het onderwerp "foto".

Greets, Rehan.

**Comment by HiddeStatema** [comment]
Ik wil je best helpen maar ik heb de nieuwspagina gekozen. Maar ik wil je best in de lessen helpen!
