### ISSUE TITLE
Vraag / Hoe om te gaan met browser font verschillen?

### ISSUE THREAD

**Issue by fabianvdwulp** [CMDA/mi-mobile-design-forum#28]
Ik heb gemerkt dat er erg veel verschil in geïmporteerde fonts zit. Of dit nou fonts zijn van de google fonts api of zelf geïmporteerde fonts met @font-face. Zie hieronder drie screenshots met verschillen.

Chrome mac, Hier is de font zoals ik hem wil:
http://puu.sh/8BhXh/9f07877272.png

Chrome Windows, fontje wordt rafelig bij rondingen, fontje krijgt minder font-weight en meer letter-spacing:
http://puu.sh/8BhXw/68a504fe76.png

IE11 Windows, blijft die wel redelijk strak maar ook de font-weight is minder en meer letter-spacing:
http://puu.sh/8BhXF/311a67b880.png

Nou vind ik de letter spacing verschillen niet zo een ramp, maar als een font op kleiner formaat wordt getoond en de rafeligheid overheerst en daarnaast de font-weight ook afneemt, gaat de leesbaarheid erg achteruit. 

Mijn vraag dan ook. Zijn er hier oplossingen voor of is het te voorkomen met simpele css 'trucjes'?

**Comment by bramswier** [comment]
Er blijven altijd verschillen in hoe fonts worden gerenderd in verschillende browsers op verschillende OS-en. <a href="http://css-tricks.com/font-rendering-differences-firefox-vs-ie-vs-safari/">Hier op CSS-tricks een artikel</a> die dit uitlegt. 

Er is een CSS3-manier, font-smooth, maar deze is <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth">non-standard</a> en wordt maar op zeer weinig browsers ondersteund. Mozilla raadt het gebruik daarvan dan ook af. Ook zitten er, naast de slechte support en onverwachte uitkomsten, nog meer <a href="http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/">nadelen</a> aan deze techniek.
