### ISSUE TITLE
Bevinding / CSS ~

### ISSUE THREAD

**Issue by IAmABear** [CMDA/mi-mobile-design-forum#30]
Ik zat toevallig vandaag zelf in de les met de vraag wat de "~" doet in CSS. Er zullen vast mensen zijn die dit weten echter ik heb het uitgezocht en kwam op het volgende:

General sibling combinator
The general sibling combinator is made of the "tilde" (U+007E, ~) character that separates two sequences of simple selectors. The elements represented by the two sequences share the same parent in the document tree and the element represented by the first sequence precedes (not necessarily immediately) the element represented by the second one. (source: http://www.w3.org/TR/selectors/#adjacent-sibling-combinators ).

Het mooie hiervan is dat je met css de hover kan gebruiken om zo meerdere div's te verplaatsen en/of te veranderen. Als iemand hier ooit al mee gewerkt heeft, deel a.u.b. je werkt en laat zien wat er allemaal mee kan. Ik ben momenteel met een menu bezig die dit gebruikt, op het moment dat deze werkt zal ik deze hier posten.

**Comment by vasilisvg** [comment]
Kijk uit met het gebruik van `:hover`. Het is namelijk niet helemaal duidelijk hoe het zich moet gedragen op touch-screens waar zoiets niet bestaat. We gaan het daar later in de lessen nog wel over hebben, maar kijk alvast eens naar de `:target` pseudo-selector als alternatief

**Comment by IAmABear** [comment]
Ik merkte al dat hover "vaag" reageerde, als in het wilt als een knop reageren maar bugt vervolgens de hele tijd. Ik was echter niet van plan :hover te gebruiken voor mobiel, dit wil ik uiteindelijk vervangen door of een simpele klik bare rand (of liever) gestures. Echter we zitten nu puur en alleen met html/css te spelen en dit was nieuw voor mij dus ben er nu even mee aan het spelen.

**Comment by IAmABear** [comment]
Een korte vraag over de `:target` , zover ik tot nu toe heb gezien werkt het alleen wanneer je 'jumping behaviour' wilt. Oftewel met `<a href="#divName">`. Is het alleen mogelijk met het gebruikt van `<a href="#divName">` of zijn er andere manieren? Want met de het linken d.m.v. a href word de URL er niet echt mooier op plus er zijn nog wat bugs met het terug gaan naar het vorige element (wat ik juist nodig heb).

**Comment by vasilisvg** [comment]
Het werkt inderdaad alleen met skiplinks. Overigens gaan we vanaf volgende week pas echt naar interactie kijken. Je kan je nu beter concentreren op vormgeving en layout.
Mocht je dat allemaal al echt af hebben probeer het dan zo simpel mogelijk te houden. Wat je aan het doen bent klinkt nu al complex (-:
Werkt het wel op een zwart/wit kindle?

**Comment by IAmABear** [comment]
Tot nu toe werkte (ik was gewoon wat aan het testen/rondkloten) zelf op een Motorola RAZR V3m. Ik gebruik momenteel de `:hover` als test om te kijken hoe verschillende browsers op de formaten werken en dergelijke. Daarnaast zou het gewoon op een zwart wit kindle moeten werken sinds mijn website momenteel uit 3/4 kleuren bestaat, waarvan een lichte achtergrond en een donkere voorgrond (tekst). Dus zelfs al zou het zwart wit zijn zouden de kleuren goed moeten doorkomen. Dit heb ik jammer genoeg nog niet kunnen testen sinds ik geen kindle heb en de tools die ik gebruik alleen de browser eigenschappen neemt en niet kleur in rekening neemt.

Voor de rest de complexiteit valt mee, als iemand op vakje x klikt gaat dat vakje naar rechts, echter door alle devices wil ik het overal op kunnen ondersteunen door een klik functie en voor browsers b.v. een `:hover` en mobile platforms gestures o.d. d.m.v. javascript. Dit is echter meer ook omdat ik nog nooit met gestures heb gewerkt en dit eens wil gebruiken.

**Comment by IAmABear** [comment]
Oke best wel handig, je kan in `-webkit-filter: grayscale(100%) brightness(10%) contrast(100%);` gebruiken om je website een 'grijze tint' te geven. Is niet een 1 op 1 vergelijking met de kindle maar het werkt voor nu.
