### ISSUE TITLE
Wat voor lay-out gebruiken jullie voor je foto site?

### ISSUE THREAD

**Issue by casdekker** [CMDA/mi-mobile-design-forum#31]
Als ik rond kijk op foto sites zie ik voornamelijk grid lay-outs of lay-outs met een gecentreerde grote (fullscreen) foto. 

Ik zit in dubio over hoe 'complex' je moet gaan met een lay-out voor een foto site. Naar mijn mening is de foto de content en (dus) de lay-out. Ik zie dan ook vooral scherm vullende foto weergaven zitten.

Wat voor lay-out gebruiken jullie op je foto site en waarom?

**Comment by IAmABear** [comment]
Ik gebruik momenteel een combinatie van op veel plekken. Ik heb de portfolio van Dhr. Ritmeester voor me genomen als doel, hierdoor kan ik makkelijker visualiseren wat er op moet komen plus  er zijn twee soorten content: tekst en foto, wat ik interessant vind. Als je een  fotowebsite in het algemeen neemt zou je je meer op de foto kunnen focussen en de tekst erin verwerven. 

Ik ben momenteel nog bezig om de lay-out om te gooien sinds ik ineens iets anders leuks zag, echter je kan zien waar ik momenteel mee bezig ben op:
http://dev.floydvanboksel.com/hva/designformobile/

Het is nog buggy op aardig wat plaatsen sinds ik momenteel er mee aan het spelen ben hoe het reageert op verschillende browsers en mobiel is het nog niet te gebruiken i.v.m. dat ik hovers gebruik om me menu te testen.

Anyhow, by de bearception pagina ben ik zeg maar met een fullscreen foto aan het experimenteren hoe ik dit kan weergeven en wat de mogelijkheden hiertoe zijn. Op de pagina http://dev.floydvanboksel.com/hva/designformobile/flexbox.html ben ik met flexbox bezig om te kijken hoe ik meerdere verhalen met foto's kan vertellen. Als ik hier een beetje stabiele versie van heb gooi ik hem tussen het normale menu alleen ik hou hem er nu nog tussenuit i.v.m. buggyness. Echter kan je wel kijken hoe ik ermee bezig ben, misschien kom je op ideeën omdat je vind dat ik het compleet fout doe :D

Daarnaast ben ik  tekstueel is nog veel aan het experimenteren om te kijken wat het meest bevalt, je zal daardoor ook veel random zooi zien verschijnen. De reden hiervoor is ookal staan foto's misschien centraal zit er altijd een verhaal bij zowat. Dit word tekstueel verteld en moet de foto dus goed ondersteunen. 

Als je voor de rest vragen heb over iets op de website of fotowebsite in het algemeen pb me maar op facebook.

**Comment by casdekker** [comment]
Ik zie dat je op je Bearception pagina de afbeelding zowel een height als een width van 100vw/100vh mee geeft, dit betekent wel dat als de afbeelding niet eengelijke aspect ratio als de viewport heeft de afbeelding stuk gaat.

Waar ik vooral mee zit is het weergeven van een foto zodat de foto exact overkomt zoals deze is bedoelt. Ik kan begrijpen dat bij een vakantiekiekje het niet uitmaakt als er een stukje van af wordt gesneden, maar als professioneel fotograaf lijkt het me dat je de werking van je foto ook online over wilt laten komen.

Neem bijvoorbeeld  de foto Rhein II  van Andreas Gursky (duurste foto ooit geveild, 4.338.500 dollar):  
![image](https://cloud.githubusercontent.com/assets/3510250/2936431/d6276740-d85b-11e3-813a-108698b8cf82.png)

De schoonheid van deze foto ligt volgens de experts in de verhouding van de middellijn met de andere lijnen. Dit is iets wat je lijkt mij behouden wilt houden op het web. 

Hier valt uiteraard wat voor te verzinnen door hem niet fullscreen weer te laten geven, ook heeft deze foto weinig attributen in de foto. 

Vind jij dat je voor elke foto individueel moet bepalen hoe je deze weergegeven wilt hebben op device? (heb het hier dan over het portfolio van een professional)

**Comment by IAmABear** [comment]
Ik zou niet voor elke foto een aparte layout/stijl maken. Echter daar zit ik nu ook mee te spelen, de vmin en vmax. Veel foto's die ik gebruik zijn vierkant en worden soms uitgerekt. Echter bij veel landscape foto's wil je juist dat hij in de breedte langer is dan hoogte. Ik zit nu een beetje te kijken hoe foto's reageren wanneer ik b.v. `width: 20vmin; height: 10vmin;` doe. Ik heb zelf issues met verschillende schermen en dat afbeeldingen in sommige afmetingen wel uitgerekt moeten worden tenzij je witruimte wil laten creeeren (voornamelijk met fullscreen achtergronden).

Ik zal als ik jou was ook kijken naar de vmin om zo afbeeldingen in hun stijl te houden en de rest op te vullen met blanco achtergrond in dit geval. Want een foto die zo duur is wil je optimaal tonen en wat witruimte eromheen lijkt mij dan (persoonlijk) niet zo erg.
