### ISSUE TITLE
Question / flexbox

### ISSUE THREAD

**Issue by IAmABear** [CMDA/mi-mobile-design-forum#36]
Momenteel beetje aan het kijken wat flexbox allemaal kan. Echter heb ik de vraag hoe je verschillende "boxex" onder elkaar laat komen en dat ze naast elkaar springen wanneer de hoogte van het scherm is bereikt. 

Ik weet dat het volgende nodig is om ze onder elkaar te krijgen en naast elkaar indien de pagina hoogte is bereikt

Container

```
#flex-container {
    width: 65vw;
    margin: 0 auto;
    margin-top: 5vh;
    display: flex;
    flex-flow: row;
    justify-content: left;
    align-items: start;
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```

Basic box

```
.portfolio-article {
    width: 10vw;
    word-break: break-word;
    margin-right: 4vmin;
    margin-bottom: 2vmin;
}
```

Het probleem wat hier echter mee ontstaat in dat wanneer er zowel in de hoogte van de pagina geen ruimte is EN geen ruimte meer aan de zijkant, dat flexbox zich uit blijft breiden naar de rechterkant van het scherm. Hier zou ik graag willen dat hij dan meer ruimte in de hoogte neemt. Maar alleen pas wanneer hij in de breedte te groot word.

Iemand enig idee hoe je dit doet? Of een richting kan geven zodat ik weer verder kan?

**Comment by joostf** [comment]
Ik zou proberen de .portfolio-article items een max-width te geven ipv een width..

**Comment by IAmABear** [comment]
de .portfolio-article een max-width te geven i.p.v. een width maakte geen verschil. Plus hun breedte is momenteel nog niet mijn hoofd probleem. Tis meer dat ik niet wil dat hij ineens rechts van het scherm doorgaat met artikelen plaatsen. 

Ik laat dit anders wel tot na dinsdag liggen want ik moet dan ook nog wat hebben om op te leveren
