### ISSUE TITLE
<bevinding> / <bestel flow>: <onderzoeksresultaten>

### ISSUE THREAD

**Issue by aproskam** [CMDA/mi-mobile-design-forum#37]
Heb een enquête opgesteld om wat meer informatie te krijgen over de webshop gebruikers en ondertussen heb ik ook al wat resultaten.
Momenteel door 34 mensen ingevuld.

Resultaten zijn hier te vinden:

https://docs.google.com/forms/d/1dOEivPA8L2UULT-x8ut29Hedx-A4BRl0CcktscCq_eo/viewanalytics

**Comment by aproskam** [comment]
Om nog meer resultaten te verzamelen kan je deze link delen zodat mensen de enquête kunnen invullen:

https://docs.google.com/forms/d/1dOEivPA8L2UULT-x8ut29Hedx-A4BRl0CcktscCq_eo/viewform

**Comment by vasilisvg** [comment]
Reactie van Peet Sneekes op twitter: http://twitter.com/peetsneekes/status/465464974245396481

**Comment by aproskam** [comment]
Nice! Teller staat nu op 41!

Google moet blijkbaar nog wel werken aan een responsive web versie

**Comment by rappel93** [comment]
Bedankt voor het onderzoek. Hier hebben wij zeker wat! Helaas zijn sommige vragen half half qua resultaten. Hier zit dus nog een twijfel
