### ISSUE TITLE
Vraag / Bestelflow : Layout

### ISSUE THREAD

**Issue by Barry91** [CMDA/mi-mobile-design-forum#38]
Bij het ontwikkelen van mijn bestelflow heb ik eerst alle losse stappen bedacht en vervolgens ben ik gaan nadenken over de juiste layout. Hierover heb ik alleen nog mijn twijfels. Opties die ik hiervoor vond zijn een one-page checkout en een stappen checkout en de vraag die ik eigenlijk heb is hoe andere studenten tegen deze opties aankijken. Aan de ene kant heeft een stappen checkout naar mijn mening een betere begeleiding door het bestelproces en hebben we controle over de volgorde van de stappen, waardoor het bijv. mogelijk is om de gebruiker eerst te laten inloggen met zijn Paypal account, waarna persoonsgegevens automatisch kunnen worden ingevuld. Aan de andere kant is een one-page checkout overzichtelijk en snel. Ook vroeg ik me af, wanneer ik kies voor de stappen checkout, op welke manier ik het beste de verschillende stappen doorlopend kan maken, door bijv. het tonen en verbergen van stappen met Javascript of de stappen in verschillende HTML pagina's op te delen. Dit maakt het posten van de data wel een stuk lastiger, maar aan de andere kant kan een stappen checkout met Javascript problemen opleveren, wanneer Javascript is uitgeschakeld of niet compatible is met oudere devices/browsers.

Op het internet vond ik de volgende twee artikelen die gaan over One-page checkout vs een stappen checkout, maar ook na het lezen van deze artikelen blijft mijn twijfel.

http://baymard.com/blog/one-page-checkout
http://www.getelastic.com/single-vs-two-page-checkout/

**Comment by fabianvdwulp** [comment]
Lastige keuze inderdaad. Je kaart aan dat bij een stappen bestelflow je bv met paypal de gebruiker kan laten inloggen en dan de gegevens automatisch kan laten invullen. Dit kan uiteraard ook met een one page check-out. Bij de one page versie zou ik dan gaan voor ingeklapte tabjes behalve de eerste. Hier voer je een actie uit(bv inloggen) en dan klapt het tweede stukje omlaag en door tot alle stappen zijn gedaan. Ik zou de gemaakte stappen daar in tegen niet dichtklappen. Ik persoonlijk vindt het fijn om constant te zien wat ik heb ingevoerd ( adres en mijn bestelling) om te zien of  alles nog klopt. 
Ik denk dat je keuze meer moet afhangen van de lengte van je bestelformulier. Stel ik wil een boektje online bestellen voor iemand. Dan moet ik mijn adresgegevens invullen, betaalgegevens, dan adresgegevens van de gene naar wie ik het boeketje stuur, een kaartje toevoegen, datum kiezen en evt nog extra's toevoegen zoals een vaas. Dit past nooit op een one page formulier want dan ben je het overzicht kwijt. 
Als jou bestelproces kort en to the point is, zou ik voor een one page bestelformulier gaan.
