### ISSUE TITLE
Vraag / Nieuwssite: Ratio behouden bij het schalen van artikelafbeeldingen

### ISSUE THREAD

**Issue by bramswier** [CMDA/mi-mobile-design-forum#40]
Op de homepage van mijn nieuwssite wil ik een overzicht van de artikelen plaatsen. Een gedeelte hiervan bestaat uit een (klikbare) afbeelding met de titel van het artikel er onder. Omdat de website responsive is, schalen de afbeeldingen mee (img staat op width: 100%;). Omdat er afbeeldingen van verschillende groottes worden gebruikt, moet er een vaste/maximum hoogte worden ingesteld aan de afbeelding om verschillen in hoogte tussen afbeeldingen naast elkaar te voorkomen. Door dit te doen verliest de afbeelding zijn aspect ratio, wordt hij niet mooi en schaalt deze ook niet meer mooi mee. Dit probleem is veel te vinden op internet:

http://www.sitepoint.com/maintain-image-aspect-ratios-responsive-web-design/
http://stackoverflow.com/questions/3751565/css-100-width-or-height-while-keeping-aspect-ratio

De oplossing die ik nu heb toegepast, is met een background-image. Ik heb mijn voorbeeld hier staan, zodat deze ook aangepast kan worden: http://jsfiddle.net/pHJ3B/4/.

Mijn vraag is: lopen jullie ook tegen dit probleem aan? Hoe zouden jullie dit oplossen?

**Comment by martijnroosenhart** [comment]
Ik heb het zelfde probleem. Ik denk voor nu dat ik het gewoon ga oplossen door de foto's handmatig op maat te maken. Ik denk ook dat foto's voor een nieuwssite altijd met een camera gemaakt worden en dus ook eigenlijk altijd dezelfde verhouding hebben. 

Ook kan je, je layout er op aanpassen. Kijk bijvoorbeeld eens naar:
http://www.haarlemsdagblad.nl
De hoogtes van de artikelen verschillen. 

Je oplossing in de css met background-image is ook wel een goed idee. Daar ga ik ook nog even naar kijken.
