### ISSUE TITLE
Vraag / Nieuwssite: In app-vorm? Of echt in website-vorm? Of zelfs een mix van?

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#41]
Hey jongens,

Op het moment ben ik bezig met het uitwerken van m'n nieuwssite. De vorige artikelen hebben mij geïnspireerd om van de site een webapplicatie maken, en dus ook geheel richting software design te gaan. Echter loop ik tegen een keuze aan, waar ik niet zo snel uit kom:
- Mijn hoofdpagina (http://rizkicalame.com/dfm/) heeft dus een full-page design, elk witruimte wordt opgevuld met content en hij zal dus ook responsive reageren.
- Echter, heeft mijn artikelpagina (http://rizkicalame.com/dfm/article.html) dit niet. Er wordt veel witruimte gebruikt om de leesbaarheid te bevorderen en ook de content zelf is gecentreerd. (Wie wilt er nou lezen uit een klein kolommetje van 20em, die links is uitgelijnd, toch?)

Mijn vraag aan jullie is, is het slim om het artikelpagina om te toveren naar een full page design? Hoe zou het er dan uit moeten zien? Waarom wel en waarom niet?

(P.S. Excuses als het een en ander veranderd aan mijn site terwijl jullie het aan het bekijken zijn, ben er namelijk druk mee bezig!)

**Comment by sjoerdvalk1991** [comment]
Ik heb hier ook naar gekeken en heb mijn breedte al meerdere keren aangepast in de media queries. Op full-screen mode ben ik nog op zoek naar de juiste breedte voor een artikel.
 http://valk-multimedia.com/nieuwssite/artikel.html

**Comment by oledi** [comment]
zelf ben ik niet met de newssite bezig, maar ik vind op het moment de artikel pagina wel beter lezen dan je mainpage. Ik zou het voor de artikel dan ook hierop laten. Wel kan je nog kijken naar consistensie, msg kan je de grote foto op de mainpage ook naar het midden zetten? Dit maakt iets meer sense bij de pageswap imo.
