### ISSUE TITLE
CSS Support voor browsers

### ISSUE THREAD

**Issue by ghost** [CMDA/mi-mobile-design-forum#42]
Weet iemand een goede website waar je CSS support voor verschillende browsers (en versies) kunt vinden?

**Comment by TDMW** [comment]
<del>Op w3schools staat een redelijk groot overzicht van alle CSS3 compatibilty met een hoop versies van browsers: http://www.w3schools.com/cssref/css3_browsersupport.asp</del>

**Comment by vasilisvg** [comment]
Ai. Puntje er af Bart. Het is verboden om naar W3schools te linken. Hoe maak je dit nog goed?!

Betrouwbare compatibilitytabellen zijn op http://caniuse.com/ te vinden
