### ISSUE TITLE
Vraag/nieuwssite /Juiste weergave overzichtspagina artikelen, met of zonder foto?

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#43]
http://valk-multimedia.com/nieuwssite/

Ik ben op zoek naar de juiste manier van weergeven van de overzichtspagina.
Op fullscreen en op tablet wil ik de foto behouden, maar op smartphone neemt de foto al gauw te veel ruimte in.

Verder gebruik nu op de artikelpagina
http://valk-multimedia.com/nieuwssite/artikel.html
justify om de kolom aan twee kanten uit te lijnen. Vaak vallen er op deze manier witruimtes tussen worden als de schermgrootte wordt aangepast. Hoe kan ik dit voorkomen, zonder dat de kolom er rommelig uit ziet.

**Comment by rappel93** [comment]
Op mobiel zal ik alleen de belangrijkste artikelen met een foto plaatsen. Ik ben bang dat het anders heel druk gaat worden als je overal een foto bij gaat plaatsen

**Comment by TVoorend** [comment]
Ik zat even naar je code te kijken, alleen de media querys waren in px.
