### ISSUE TITLE
Dropdown menu bij lagere resolutie

### ISSUE THREAD

**Issue by JanJurre** [CMDA/mi-mobile-design-forum#44]
Ik ben opzoek naar een manier om bij een lagere resolutie, mijn menu naar een icoon te verplaatsen en dat deze dropdown uitklapt (zoals bij <a href="http://www.theguardian.com/uk?view=mobile#opt-in-message">The Guardian</a>)

**Comment by IAmABear** [comment]
Je kan met media queries de layout opniuew schrijven zodat je menu een drop down icoon word

**Comment by vasilisvg** [comment]
[Hier kan je daar een simpel voorbeeld van vinden](https://fronteers.nl/_downloads/2011/haaien/stap-11/).

**Comment by IAmABear** [comment]
God wat is dat effectje op die website hinderlijk na een paar keer xD Wel leuk bedacht
