### ISSUE TITLE
<Vraag>/<bestel flow>: <fieldset caption>

### ISSUE THREAD

**Issue by aproskam** [CMDA/mi-mobile-design-forum#45]
Klopt het dat je de caption van een fieldset in een form, niet kan stylen?

Ik probeer er achter te komen hoe het zit, maar kom er niet zo snel achter.

Iemand hier ervaring mee?

**Comment by vasilisvg** [comment]
Wat is de _caption_ van een `fieldset`? Of bedoel je misschien de `legend`? Die is inderdaad moeilijk te stijlen. Maar het schijnt dat het een stuk beter kan als je een `span` in die `legend` stopt.

**Comment by aproskam** [comment]
Ah oke, dacht dat je voor fieldset caption gebruikte maar blijkbaar is het dus legend. Thnx, met span moet het inderdaad wel gaan lukken!
