### ISSUE TITLE
Question / Viewport

### ISSUE THREAD

**Issue by IAmABear** [CMDA/mi-mobile-design-forum#46]
Voornamelijk gericht @vasilisvg. Ik ben de afgelopen week voornamelijk bezig geweest met viewporten en zowel tekst als layout hier op te focussen. Echter toen ik ging nalezen naar de beschikbaarheid/ging testen op een oude safari browser werkte het niet. Mede door dit artikel http://caniuse.com/viewport-units dat viewports nog slecht worden ondersteund en op oudere browsers niet.

Met oog op het eindproduct dat overall moet werken, maakt dit het gebruik van viewports niet onhandig? Het zou alsnog kunnen echter voor alles wat je doet zal je alsnog een percentage fallback of em moeten defineren. Moet ik voor dit vak alle die fallback erin moeten bouwen indien ik viewports e.d. wil blijven gebruiken?

**Comment by vasilisvg** [comment]
Er zijn twee manieren om iets nieuws als de _viewport relative units_ te benaderen. De eerste is door het in te zetten als _de oplossing_ en daarna een fallback te maken voor oudere browsers. De tweede is door deze units puur te zien als een _enhancement_ voor als het ondersteund wordt. Wij werken nu volgens de tweede methode. Zorg er dus voor voor dat het bruikbaar is als je die units niet tot je beschikking hebt. Niet kapot. En zorg er voor dat het superfijn is voor mensen die hun browser wel (kunnen) updaten.

**Comment by IAmABear** [comment]
Oke dan ga ik in dat geval maar weer eens flink aan de bak, bedankt voor het snelle antwoord.
