### ISSUE TITLE
bevinding - css vormgeving in browser

### ISSUE THREAD

**Issue by TVoorend** [CMDA/mi-mobile-design-forum#47]
Wat ik doe en voor sommige zelfsprekend is. Dat ik bij het vormgeven van elementen dit eerst in de browser doe. Vervolgens kopieer ik het dan naar de editer.

**Comment by aproskam** [comment]
Dit doe je doormidden van een ontwikkelaars console? Chrome heeft er 1 standaard in de browser verwerkt maar voor Firefox heb je hier een plugin voor nodig zoals Firebug

**Comment by vasilisvg** [comment]
Firefox heeft inmiddels ook een prima eigen developer omgeving. Geen plugin meer voor nodig.
