### ISSUE TITLE
Waar de weekopdracht te uploaden/hoe?

### ISSUE THREAD

**Issue by TDMW** [CMDA/mi-mobile-design-forum#5]
Misschien ben ik wel erg lui, misschien kan ik het compleet niet vinden en misschien snap ik geen hol van Github. Maar kan iemand mij uitleggen waar ik de 'kale html' opdracht van deze week moet uploaden? En waar ik uberhaupt de uitleg/criteria van deze opdracht kan vinden, ik ben niet echt bekend met github dus het is nogal een partij zoeken voor mij. 
- Bart

**Comment by sjoerdvalk1991** [comment]
He Bart,

De 'kale' html maak je voor je eigen opdracht. Bij eventuele problemen of oplossingen die  je bij jouw 'kale' html tegen komt kun je hier een issue posten. De opdracht hoeft dus niet ingeleverd te worden, maar moet gewoon voor de volgende les af zijn zover ik weet.
