### ISSUE TITLE
Vraag: Responsive menu vormt niet terug als ik mijn window weer groter maak

### ISSUE THREAD

**Issue by TDMW** [CMDA/mi-mobile-design-forum#51]
Yo! Zoals iedereen nu hard aan de slag met CSS gegaan, echter stuit ik op een error waar ik even niet uitkom. De url van mijn website is de volgende: http://klikcheck.com/dfm/

Zodra mijn schermbreedte onder de 800 (en 400) px komt, zet ik mijn list elementen (in een UL in een nav) op clear: both en float: center, om te zorgen dat ze onder elkaar komen te staan. Dit werkt allemaal lekker prima, totdat ik weer terug wil gaan naar een grotere schermbreedte. Dan blijven ze onder elkaar staan en gaan ze niet meer terug naar de oorspronkelijke variant waar ze netjes naast elkaar staan.

Wat moet ik hier doen? Kan ik beter een andere manier van aanpak gebruiken om het menu aan te passen? Ik ben geen HTML/CSS koning, dus hulp wordt gewaardeerd!

**Comment by IAmABear** [comment]
De reden die ik even snel kan vinden is dat je in je media querie het volgende hebt staan:

```
@media (max-width: 800px) {
   nav ul li {
    clear: both;
    float: center;
}
```

Dit deel zorgt er voor dat ze onder elkaar komen te staan zoals je zelf al zegt. Echter zie ik niet dat je in een andere media querie het weer naar zijn originele staat herstelt. ( Ik durft niet met 100% zekerheid te zeggen dat het onderstaan 1:1 werkt maar het geeft in ieder geval een idee. ) Je krijgt dan iets als hieronder:

```
@media (max-width: 1000px) {
   nav  ul {
    list-style-type: none;
    display: inline;
   }

   nav  ul li {
    float: left;
   }
}
```

Indien je er hiermee niet uitkomt stuur me even een bericht op fb of hier dan kijk ik met je mee en lossen we het samen op
