### ISSUE TITLE
URL's medestudenten

### ISSUE THREAD

**Issue by IAmABear** [CMDA/mi-mobile-design-forum#52]
Misschien leuk om ook te kijken wat de rest doet, plaats jouw link naar jouw werk hieronder in de comments zodat we elkaars werk ook kunnen bekijken en eventuele tips e.d. kunnen geven.

Mijn link (Floyd):
http://dev.floydvanboksel.com/hva/designformobile/

**Comment by sjoerdvalk1991** [comment]
http://valk-multimedia.com/nieuwssite/versie2/

**Comment by HiddeStatema** [comment]
http://nieuws.creatinq.com/
Met nieuws van nu.nl!

**Comment by casdekker** [comment]
http://viewlab.nl/portfolio

mijn focus ligt op afbeelding optimalisatie

**Comment by sjoerdvalk1991** [comment]
Nice Hidde! 

Voor smartphone en tablet een hele mooie toepassing.
Maar voor pc ook een ideale toepassing? soms kom ik de scroll niet meer uit.
Hoe ga je dit optimaliseren?
