### ISSUE TITLE
Bevinding / Nieuwssite <Nieuwsitems uitklappen en opdelen in verschillende secties >

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#54]
Ik heb vooral gekeken naar een lang artikel. 
Voor smartphone lijkt me het heel interessant als je zoals bij dit experiment een artikel uitklapt en daarin weer meerdere delen van een artikel kan uitklappen. Hier zou je bepaalde verdiepingen kunnen toevoegen.

http://valk-multimedia.com/nieuwssite/accordion/

Als je het artikel van 'Obama vermoord' uitklapt. Dan kan je daarin weer meerdere secties uitklappen voor bepaalde bijlagen over dit artikel. 
Hoe denken jullie hierover?
Het uitklappen van een artikel is voor mobiel in mijn ogen net zo gemakkelijk voor de leesbaarheid als een aparte artikelpagina.

**Comment by JanJurre** [comment]
Ziet er wel cool uit! 
Ik keek er alleen gek tegenaan dat de subkopjes in het artikel dezelfde opmaak hebben als de artikelen. Dit veroorzaakte een beetje verwarring bij mij.

Is er ook een mogelijkheid om te scrollen "binnen" het uitgeklapte deel?
Want als ik "Obama vermoord" en daarna "Obama in 8 jaar" uitklap, verdwijnt er een heel stuk achter de Paus die uit de kast komt ;)

**Comment by sjoerdvalk1991** [comment]
Ja i know, dat komt omdat de uitklapbare delen een hoogte meekrijgen in pixels in dit voorbeeld dat ga ik nog even fixxen
