### ISSUE TITLE
Voor de flexboxers, een complete uitleg

### ISSUE THREAD

**Issue by vasilisvg** [CMDA/mi-mobile-design-forum#57]
Flexbox gebruiken is een ding, het echt begrijpen is iets anders. En een stuk lastiger. Gelukkig heeft Chris Coyier deze [Complete Guide to Flexbox](http://css-tricks.com/snippets/css/a-guide-to-flexbox/) geschreven. Doe er je voordeel mee.

**Comment by arjentnkmp** [comment]
Thanks! Ik ga ermee aan de slag als ik een uurtje over heb.
