### ISSUE TITLE
Nieuws site? en ff share button's er bij knallen? Misschien niet zo handig als je dacht...

### ISSUE THREAD

**Issue by StephanBosma** [CMDA/mi-mobile-design-forum#59]
In een artikel over share buttons + een poll op css-tricks.com blijkt dat toch veel mensen gewoon het linkje kopiëren ipv de share buttons te gebruiken. http://css-tricks.com/new-poll-sharing-buttons/ dit heb ik gevonden iemand anders een ander inzicht?

**Comment by MilanDembinski** [comment]
Ik vind het eerlijk gezegd wel handig, ik stuur vaak nieuwsberichten op nu.nl door naar vrienden. Ik heb een artikel gevonden over verschillende opties met plus en min-punten: http://mashable.com/2011/03/11/add-social-sharing-buttons/
