### ISSUE TITLE
Vraag: RAW afbeelding omzetten naar YCrCb kleurmode in Photoshop (of Lightroom)?

### ISSUE THREAD

**Issue by casdekker** [CMDA/mi-mobile-design-forum#60]
Weet iemand hoe ik een (RAW geschoten) afbeelding in Photoshop/Lightroom direct kan omzetten naar de YCrCb kleurmode? Als in een goede tool, plugin of een ander programma?

Additionele informatie:
Ik wil gaan kijken naar het maximaal optimaliseren van een afbeelding op het gebied van kwaliteit versus bestandsgrootte. Om dit te doen schijnt een YCrCb kleurmode betere resultaten te geven dan de standaard RGB mode.De meeste dSLR's schieten RAW in de YCrCb kleurmode, omdat hier het licht kanaal gescheiden zit van de kleur kanalen is hier veel sterker in te compressen (het menselijk oog haalt de meeste informatie uit het licht kanaal, dus de kleur kanalen kunnen gecompressed worden). Ik ben vooral geïnteresseerd in het weergeven van grote foto's op de site en dan het liefst in een zo'n hoog mogelijke kwaliteit.

**Comment by Barry91** [comment]
Heb je iets aan dit artikel: http://www.impulseadventure.com/photo/chroma-subsampling.html

**Comment by casdekker** [comment]
Dat artikel had ik inderdaad gezien, biedt helaas geen antwoord op mijn vraag maar eerder een uitleg over de techniek.
