### ISSUE TITLE
Vraag: Gebruik maken van hyphens bij een nieuwsartikel, of niet?

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#61]
Hey guys,

Momenteel ben ik bezig met het 'perfectioneren' van mijn nieuwspagina. Nu ben ik beland bij de keuze of ik gebruik wil maken van hyphens of niet. Ik vind ze zelf echt spuug en spuuglelijk. Echter ben ik wel van mening dat hyphens toch een positieve bijdrage kunnen leveren aan de leesbaarheid van een artikel. 

Voor degenen die niet weten wat een hyphen is; het is wanneer een woord te lang is om een regel mee te vullen, waardoor het afgebroken wordt en een '-' ertussen geplaatst wordt. Wat je dan krijgt is:
"submi-
tting"

Heeft iemand hier advies over? Of heeft iemand toevallig een artikel gelezen ergens waarin het gebruikmaken van hyphens toegelicht worden?

Also, dit is mijn artikelpagina: http://rizkicalame.com/dfm/article.html

**Comment by IAmABear** [comment]
Persoonlijke mening:
Ik ben niet echt een fan van hyphen, merendeels omdat het vaak niet lekker leest. Echter ik merk daardoor dat op bepaalde pagina's ontiegelijk veel witruimtes ineens ontstaan. Echter prefereer _ik_ witruimtes boven halve woorden.

Also heb het net even opgezocht en als jet het met de css hyphens wilt gaan doen, deze word niet al te lekker ondersteund momenteel:
http://caniuse.com/#feat=css-hyphens

**Comment by bramswier** [comment]
Toevallig ben ik er deze week ook naar gaan kijken. Waar ik zelf mee zat: als je een lang woord hebt, en je zoomt het venster heel ver in, dan wordt het woord breder dan de viewport, en ontstaat er een scrollbar. Ik wilde dus dat hij in dat geval het woord zou opbreken, en kwam daarbij ook de hyphens tegen. Ik kwam op een heel handig en uitgebreid artikel uit: http://kenneth.io/blog/2012/03/04/word-wrapping-hypernation-using-css/.

Hij komt uiteindelijk met het volgende:

```
 -ms-word-break: break-all;
word-break: break-all;

 /* Non standard for webkit */
 word-break: break-word;

-webkit-hyphens: auto;
-moz-hyphens: auto;
-ms-hyphens: auto;
hyphens: auto;

This is working in Internet Explorer 8+, Firefox 6+, iOS 4.2, Safari 5.1+ and Chrome 13+
```

**Comment by MartijnEngelkes** [comment]
Ik ben zelf niet met een nieuwssite bezig maar wat je in kranten een artikelen op internet vaak ziet is dat text uitgelijnd wordt. Misschien is dat een oplossing. Het is maar net wat je mooi vindt denk ik. 

dus of:

![schermafbeelding 2014-05-19 om 18 51 18](https://cloud.githubusercontent.com/assets/7351989/3017107/ed056a86-df75-11e3-8c01-f9d8f273451c.png)

of:

![schermafbeelding 2014-05-19 om 18 51 35](https://cloud.githubusercontent.com/assets/7351989/3017109/f32ed956-df75-11e3-8ed3-321e70517e6c.png)

Volgens mij als je het uitlijnt en het te lange woord op de volgende regel zet is je regel toch mooi gevuld. 

Geen idee of je er iets aan hebt of dat het ongeveer is wat je zoekt maar who knows.

**Comment by Barry91** [comment]
Wat is precies de reden waarom je Hyphens zou willen gaan gebruiken? Op zich vind ik de tekst van het artikel prima leesbaar, maar ik denk dat jij duidt op de witruimte die ontstaat doordat woorden niet op de regel passen. Wat Martijn volgens mij bedoelt is de CSS property "text-align: justify", mogelijk ook een oplossing. Hier een artikel over het uitlijnen van tekst, waarin ook deze property behandeld wordt: http://css-tricks.com/almanac/properties/t/text-align/

**Comment by sjoerdvalk1991** [comment]
Justify heb ik nu ook gebruikt bij mijn artikel, maar vooral op smartphone vallen er dan heel veel witruimtes. Dit vind ik storend dus was eigenlijk op zoek naar een alternatief. 
http://valk-multimedia.com/nieuwssite/artikel.html
Sommige stukken heb ik links uitgelijnd en sommige stukken uitgelijnd.

**Comment by JanJurre** [comment]
Ik had ook Justify gebruikt. Vorige week kreeg ik de feedback van Vassilis dit niet te gebruiken, om inderdaad, de vele witruimtes die vallen in sommige teksten en dit heel vervelend leest.

Een alternatief heb ik er ook nog niet op gevonden, helaas.

**Comment by rizkicalame** [comment]
Thanks voor alle feedback guys! Kan er zeker wat mee.

Also; @JanJurre, Mocht je van Vasilis geen hyphens of geen text-align: justify; gebruiken?

**Comment by ghost** [comment]
Ik gebruik vaak de oplossing die **bramswier** hierboven aangeeft. Persoonlijk vind ik ook dat je gewoon spaarzaam met hyphens om moet gaan. Hyphens is een oplossing, maar niet voor alles en altijd. _Misschien een goede discussie voor de volgende les?_

**Comment by HiddeStatema** [comment]
Zelfde als Vincent en Bram, persoonlijk vind ik het niet echt handig.. Ik maak gebruik vaak van text-align: justify. Dat lijnt ook de tekst mooi uit, en niet geklooi met die hyphens.

Inderdaad iets om in de les over te hebben, Vasilis heeft vast wel een menig ook? :-)

**Comment by arjentnkmp** [comment]
Volgens mij, als je de wetten van de Nederlandse taal hanteert, is het gewoon nodig om hyphens te gebruiken, het is een grammaticale regel. Los van dat het niet super mooi staat.
