### ISSUE TITLE
Flexbox Fallback

### ISSUE THREAD

**Issue by JBostelaar** [CMDA/mi-mobile-design-forum#62]
Aangezien, ik heel mijn lay-out heb opgebouwd met flexbox en ik zag dat het maar door 82%(http://caniuse.com/flexbox) van de browsers ondersteund word. Vraag ik me af of iemand al een goede fallback heeft gevonden?

**Comment by IAmABear** [comment]
Ik heb momenteel alles eerst in columns gedaan + inline-block.
