### ISSUE TITLE
Vraag: Menu balk over hele breedte

### ISSUE THREAD

**Issue by MilanDembinski** [CMDA/mi-mobile-design-forum#63]
Hi,

Ik heb waarschijnlijk de makkelijkste vraag maar ik kom er even niet uit. Op mijn nieuws website (http://news.milandembinski.nl/) staat een menu balk, nu wil ik die balk over de hele breedte hebben, waarschijnlijk is het gewoon een kwestie van de "nav" wat omhoog schuiven maar ik begrijp niet helemaal naar waar.

Alvast bedankt!

**Comment by martijnroosenhart** [comment]
De margin van je body weghalen helpt.
Je moet dan misschien alleen de margin bij de artikelen weer toevoegen.

**Comment by sjoerdvalk1991** [comment]
#cssmenu {
background: #36aae0;
width: auto;
margin-left: -2%;
margin-right: -2%;}
 zou ook kunnen als je bij de andere elementen de margin wil houden

**Comment by aproskam** [comment]
body {
margin: 0;
background-color: #f7f7f7;
}

#articles {
margin-top: 50px;
margin 10px;
}
