### ISSUE TITLE
vraag: Nieuwsite artikelen netjes uitlijnen.

### ISSUE THREAD

**Issue by martijnroosenhart** [CMDA/mi-mobile-design-forum#64]
Ik heb bij mijn nieuws site een hoofdartikel met daarom drie kleine artikelen naast elkaar. 
Deze drie kleine artikelen staat op bovenaan uitgelijnd.
Onder deze drie artikelen kom weer drie artikelen. Deze wil ik alleen laten aansluiten op de artikelen die erboven staan. Dit krijg ik nog niet voor elkaar. Ik kan ze namelijk alleen boven onder of in het midden uitlijnen. 

Ik wil zeg maar dit effect maken: http://www.haarlemsdagblad.nl

Ik heb nu gebruik gemaakt van inline-block. Iemand enig idee hoe ik dit kan oplossen??

**Comment by JanJurre** [comment]
Heb je ook een linkje naar je website, om te zien hoe het nu is (ook verder qua code enzo)?

**Comment by aproskam** [comment]
Zonder link even moeilijk te helpen.

Maar kan je geen gebruik maken van vertical-align?

http://css-tricks.com/what-is-vertical-align/
