### ISSUE TITLE
staande en liggende foto's

### ISSUE THREAD

**Issue by oledi** [CMDA/mi-mobile-design-forum#65]
Hey jongens, ben bij mijn foto site bezig met experimenteren voor responsive foto oplossingen, nu nog voor 1 soort foto. Heeft iemand al gekeken naar staande en liggende fotos? hoe je deze beide goed kan afbeelden op je site, en verschillende schermen?

**Comment by casdekker** [comment]
Ik heb daar ook naar lopen kijken en geëxperimenteerd met vw en vh. Het punt waar ik tegenaan liep met staande en liggende foto's is vooral de 'art direction' op kleinere schermen: wanneer dekt een totaal shot de boodschap en wanneer een specifiek element wat op klein formaat totaal weg valt. Dit kan binnenkort worden opgelost met het <picture> element. http://picture.responsiveimages.org/

Ik ben voorlopig van mening dat ook afbeeldingen 'vrij' moeten worden gelaten. Scrollen en zoomen hoeft geen misdaad te zijn, zolang een afbeelding standaard op een klein scherm formaten heeft die de viewport hoogte/breedte benaderen om de boodschap van afbeelding zo veel mogelijk over te brengen.

**Comment by oledi** [comment]
"wanneer dekt een totaal shot de boodschap en wanneer een specifiek element wat op klein formaat totaal weg valt" dat is een slimme, zal ik ook nog naar kijken bij mijn site. Heb jij ook al gekeken naar een oplossing voor browsers die nog geen viewport ondersteunen? Of houd jij het voor die browsers gewoon op een standaard grootte?
