### ISSUE TITLE
Tekst in een bepaald vlak

### ISSUE THREAD

**Issue by rappel93** [CMDA/mi-mobile-design-forum#66]
Helemaal vergeten te vragen maar ik kom ergens niet uit. Ik wil mijn fotosite over de hele breedte van het scherm trekken en dit is verschillende vlakken opdelen. Nu wil ik tussen alle foto's een vlak met tekst krijgen. 

Dus hoe krijg ik het voor elkaar om tekst in "een soort van foto" te plaatsen

**Comment by fabianvdwulp** [comment]
Wil je een tekst over het plaatje krijgen of tussen alle foto's? Heb je misschien een voorbeeld hiervan?

**Comment by rappel93** [comment]
<a href="http://nl.tinypic.com?ref=2vt40w7" target="_blank"><img src="http://i59.tinypic.com/2vt40w7.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by TDMW** [comment]
Ik zou hier losse artikelen/div's voor aanmaken en dit op deze manier met CSS zo stylen dat er margin tussen elk artikel zit. Dan in dat artikel natuurlijk de tekst/foto enzo zetten.

**Comment by fabianvdwulp** [comment]
Zoiets als dit? http://jsfiddle.net/A9sZ9/1/

**Comment by arjentnkmp** [comment]
Je kunt het doen zoals Fabian het doet, je kunt ook een div maken, en daar de tekst in zetten (misschien binnen een span), vervolgens geef je de div een background-image, die je eventueel als cover kunt weergeven met CSS.
