### ISSUE TITLE
slides van een spreekster in dusseldorf over offline-first

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#67]
https://docs.google.com/presentation/d/1kGKyvw6BsQMFcQYDagCHzBjYoqvBnSg6NDRzEyQ-edM/edit#slide=id.g337440239_013

Ter aanvulling van het artikel voor morgen misschien.

**Comment by MartijnEngelkes** [comment]
http://offlinefirst.org

Hier een interessant groep die discussiere over:

UI Conventions for Offline Apps
UX patterns
User research
Mental model discovery
Tools and techniques for building offline capable apps
Distributed systems research
Technology solutions for handling offline
Web and Native

Je kunt je aanmelden op hun github en mee discussieren.
