### ISSUE TITLE
floating objects

### ISSUE THREAD

**Issue by TVoorend** [CMDA/mi-mobile-design-forum#68]
Ik liep tegen het probleem dat ik mijn footer niet helemaal onder aan de pagina kreeg, omdat de objecten in de body float eigenschap hadden en daarom geen hoogte waarden mee krijgen.
Ik heb dit kunnen oplossen door 'overflow: auto;' op de parent van de floating elementen. 
Wie weet er nog andere manier op dit op te lossen of andere manier om geen float te gebruiken?

**Comment by arjentnkmp** [comment]
Je kunt een <div class="clear"></div> plaatsen boven de footer, en vervolgens in je CSS het volgende opnemen:

.clear {
    clear:both;
}

**Comment by JBostelaar** [comment]
Om geen extra elementen voor styling in je html te plaatsen kun je ook het after element van zijn container gebruiken. Die geef je dan een clear: both;

Hier wat meer uitleg:
http://css-tricks.com/snippets/css/clear-fix/
