### ISSUE TITLE
Interessant artikel voor de nieuwslui

### ISSUE THREAD

**Issue by vasilisvg** [CMDA/mi-mobile-design-forum#69]
The Guardian heeft een mooi artikel gepubliceerd over hoe ze [het online sport-katern interessanter, sneller en beter](http://www.theguardian.com/info/developer-blog/2014/apr/04/shortening-the-goalposts?view=mobile) kunnen maken. Lezen, begrijpen en doen!

**Comment by JanJurre** [comment]
Mooi en bruikbaar artikel.
Ik heb heir iets vergelijkbaars, maar dan van de BBC:  http://www.bbc.co.uk/blogs/internet/posts/News-responsive-design-in-beta
