### ISSUE TITLE
Tutorial suggesties

### ISSUE THREAD

**Issue by oledi** [CMDA/mi-mobile-design-forum#7]
Hey mensen, 

ik ben één van de html beginners. Heeft iemand hmtl/css tutorials die hij recommend/ goed vind? Zowel voor algemeen kennis als voor wat meer gevorderd.

alvast bedankt,

rehan

**Comment by fabianvdwulp** [comment]
Als ik jou was zou ik hier gaan beginnen: http://www.codecademy.com/tracks/web

Mocht je Codecademy niet kennen. Je kunt op deze pagina kiezen of je aan het begin wilt beginnen of dat je niveau toch al wat hoger ligt. De tutorials gaan van makkelijk(bovenaan) naar moeilijker(onderaan). Je kunt in de browser de tutorials volgen en je hebt hiervoor dus nog geen editor nodig. Bij elk item staat uitgebreid uitgelegd wat je gaat doen, hoe je het moet doen en mocht je er niet uitkomen krijg je genoeg hints. Succes ermee!
