### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by TVoorend** [CMDA/mi-mobile-design-forum#71]
Ken iemand een 'low-weight' en eenvoudige slider? bijvoorbeeld een micro lib die je gebruikt?
ik heb als onderwerp nieuws en wil meerdere sliders op 1 pagina gaan gebruiken, dus ze moeten niet te groot en druk zijn.

**Comment by bramswier** [comment]
Met Javascript neem ik aan? Je zou hier eens kunnen kijken: http://microjs.com/, een verzameling van allemaal javascript micro libraries. Effe gezocht op slider: http://microjs.com/#slider, misschien kan je daar iets mee.

**Comment by joostf** [comment]
Je zou de iDangerous Swiper eens kunnen bekijken. Dit is een responsive slider die ook op touch devices werkt!

Hartelijke groet,
Joost
