### ISSUE TITLE
Fallback voor javascript 'script' maken

### ISSUE THREAD

**Issue by TDMW** [CMDA/mi-mobile-design-forum#72]
Yo mede minoristen, 

Ik wil gebruik maken van flexslider.js (versie 2) voor op mijn fotoportfolio. Nu weet ik alleen niet hoe ik hier een fallback voor moet gaan opzetten. De meeste moderne devices/browsers kunnen dit wel aan, en ik wil hem ook gewoon weergeven op smartphones, maar het lijkt me niet echt optimaal werken voor de oudere browsers/mobieltjes. Hier wil ik dan liever een statische image of helemaal niks weergeven. Hoe moet ik dit aanpakken? moet ik een vorm van browser/device detection gaan uitvoeren?

Help me out! Thanks.

**Comment by fabianvdwulp** [comment]
Aangezien je met de Flexslider toch al jQuery gebruikt. Kan je denk ik best de jQuery.browser functie gebruiken: http://api.jquery.com/jquery.browser/. Hiermee check je de browser van de gebruiker en eventueel ook welke versie. Hij kan niet alle browsers die er zijn detecteren maar de grootse browsers pakt die sowieso. Aan de hand van de uitgelezen info kan je bepalen wel of niet de flexslider te activeren.

**Comment by vasilisvg** [comment]
Het is goed om de eerste zin bij de beschrijving van jQuery.browser goed te lezen:

> Description: Contains flags for the useragent, read from navigator.userAgent. This property was removed in jQuery 1.9 and is available only through the jQuery.migrate plugin. Please try to use feature detection instead.

Ik weet niet precies waar je de slider voor wilt gebruiken, maar de standaard fallback voor `<input type=tange>` is een gewone `input`. Als je daar hetzelfde mee kunt bereiken als met een slider dan is dat prima, natuurlijk. Maar dat hangt echt af van wat je wil.
Ik heb zelf wel eens gebruik gemaakt van [deze slider](https://github.com/freqdec/fd-slider).

**Comment by TDMW** [comment]
De slider wil ik gebruiken om (logisch) enkele foto's te weergeven op de landingspagina, als een soort van 'highlights'. Was wel even vergeten dat het niet de bedoeling was om andere scripts erbij te betrekken, maar om alles zelf te schrijven. Ik zal ook even naar die fd-slider kijken. Thanks!
