### ISSUE TITLE
Vraag: Debuggen oudere browsers

### ISSUE THREAD

**Issue by Barry91** [CMDA/mi-mobile-design-forum#73]
Is het ook mogelijk om oudere browsers als IE8/6 te debuggen, bij het testen van mijn checkout pagina in Browserstack blijken veel dingen niet te werken, maar wat er dan precies wel en niet werkt weet ik niet. Ik maak gebruik van jQuery en ik vermoed dat hier ook het één en ander mis gaat, maar graag hoor ik van iemand hoe ik het debuggen voor oudere browsers het beste kan aanpakken? 

url: www.barrywonder.nl/designformobile

**Comment by rizkicalame** [comment]
Eerlijk gezegd zou ik zoveel mogelijk Javascript proberen te vermijden, en al helemaal Frameworks als jQuery. Vooral bij oudere browsers komt het voor dat dit niet ondersteunt wordt. Een belangrijke regel die ik probeer te handhaven binnen Design for Mobile is niet proberen verder te gaan dan CSS. Hoe mooier je het probeert te maken met Javascript, hoe meer kans er is dat je app breekt.
