### ISSUE TITLE
Ondersteuning flexbox en columns

### ISSUE THREAD

**Issue by martijnroosenhart** [CMDA/mi-mobile-design-forum#74]
Even een vraagje. Ik ben aan het experimenteren met flexbox maar zie dat deze nog niet overal ondersteunt wordt. Het zelfde geldt voor columns. Heeft iemand hier al ervaring mee en gebruikt iemand dit voor zijn site? 

Hoe gaat dit in oudere browsers als ie6? Is er hier een oplossing voor of kan ik het beter  bij de standaard inline-block houden?

**Comment by sjoerdvalk1991** [comment]
http://designkarma.co.uk/blog/using-flexbox-now
Misschien heb je hier wat aan!
