### ISSUE TITLE
Vraag: Nieuwsartikel - ""Mooie"" manier om artikel plaatjes/titels te behandelen?

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#75]
Na een gesprek met Vasilis vorige week, heeft hij mij het advies gegeven om mijn artikel-pagina te pimpen (als het ware). Hij gaf enige tips over het stijlen van teksten, titels en afbeeldingen. Een van de tips die hij gaf is om eventueel de titel en/of de afbeelding over de gehele breedte te doen, zodat je daarna met de rest van de content wat anders kan doen. Nu ben ik gekomen op het volgende: 
http://rizkicalame.com/dfm/article.html

Ik vind hem mooi, maar ook weer niet. Het staat professioneel..
..maar ook weer niet. Oftewel, ik zit in een dilemma. Wat vinden jullie hiervan? Wat kan ik anders doen?

Note: Het gaat echt om het plaatje en de titel. De rest van de content wil ik zo houden. :-)

**Comment by aproskam** [comment]
Titel en afbeelding naast elkaar? Als ik het op de dekstop bekijk is de titel veelte lang, leest niet prettig.
Maar voor mobile is dit wel prettig over de hele breedte, ik zou alleen wat meer lege ruimte(padding) creëren aan de buitenkant van de titel

**Comment by arjentnkmp** [comment]
Ik zou de titel maximaal net zo breed doen als de rest van de tekst, is wat rustiger voor de ogen, hoef je niet van links naar rechts (hele breedte beeldscherm) te lezen.
