### ISSUE TITLE
Nieuwsartikel opbouw

### ISSUE THREAD

**Issue by HiddeStatema** [CMDA/mi-mobile-design-forum#76]
Voor de mensen die bezig zijn met nieuws: hoe delen jullie de artikelpagina in? Doe jij eerst titel, plaatje, tekst? Of doe je eerst plaatje, titel en dan tekst? En doe je ook iets met datum van artikel?

Ik zat zelf niet mee te kloten en ik heb nu titel afbeelding tekst. Ben benieuwd naar jullie indeling en gedachte er achter!

**Comment by HiddeStatema** [comment]
Ik zat zelf iets mee te kloten\*

**Comment by sjoerdvalk1991** [comment]
http://valk-multimedia.com/nieuwssite/versietje/

zoiets dacht ik te gaan gebruiken, waarbij je eerst de tijd ziet.

**Comment by aproskam** [comment]
@sjoerdvalk1991 om een betere indruk te krijgen kan je beter wat verschillende content(foto, titels) gebruiken

**Comment by sjoerdvalk1991** [comment]
ja ben er mee bezig!
Bedankt!

**Comment by JanJurre** [comment]
Ik heb  Titel, datum (lijkt me zeker belangrijk voor een nieuwsartikel), plaatje en dan de tekst.

Het plaatje bovenaan lijkt me erg onoverzichtelijk, aangezien je eerst wilt weten waar het overgaat (lijkt mij).
