### ISSUE TITLE
Hulp gezocht met Flexbox

### ISSUE THREAD

**Issue by TDMW** [CMDA/mi-mobile-design-forum#79]
Ik ben sinds de les van vandaag aan de slag gegaan met flexbox, alleen kom ik na een hoop gekloot niet uit het geen wat ik wil. Ik wil  3 verticale rijen van 3 divs , zodra je je beeld kleiner maakt verandert dit in 2 of 1 div per rij. Eigenlijk een grid die inklapt dus. In de div zit een tekst/img, ik wil de image niet mee laten schalen maar een max-width geven. Wanneer ik nu mijn scherm verklein, valt de image buiten de div en gebeurt er eigenlijk niet wat ik wil. Ik zit er nu even mee vast. Wie heeft meer kennis van flexbox en kan me hierbij helpen? Ik heb even het stuk code uit mijn pagina gehaald en in een jsfiddle gegooid. 

http://jsfiddle.net/b9qxZ/

Thanks!

**Comment by TDMW** [comment]
Voor iedereen die geïnteresseerd is, ik heb het opgelost door al m'n css weg te gooien en overnieuw te beginnen met de hulp van css-tricks. Het resultaat heb ik opnieuw in een fiddle gegooid: http://jsfiddle.net/6PPFF/ (al weergeeft het hier niet super vanwege het kleine output scherm in jsfiddle)

**Comment by sjoerdvalk1991** [comment]
https://vimeo.com/96406277

Misschien wordt hier nog wat nuttigs vertelt
