### ISSUE TITLE
Presentatie voor Foam - Welke onderwerpen willen we behandelen?

### ISSUE THREAD

**Issue by casdekker** [CMDA/mi-mobile-design-forum#80]
Misschien ben ik voorbarig, maar voor de mensen die de foto/portfolio site doen: is het handig om een lijstje samen te stellen van welke onderwerpen mensen nu specifiek onderzoeken zodat we gerichter onderzoek kunnen doen of onderzoek kunnen bundelen?

Ik onderzoek nu zelf vooral afbeelding optimalisatie en om vanuit een RAW geschoten dSLR foto een zo klein mogelijk bestand te krijgen. Daarnaast kijk ik naar afbeeldingen op retina schermen.

Waar kijken jullie naar en wat is waard om te presenteren?

**Comment by arjentnkmp** [comment]
Ik kijk na feedback van Vasilis nu vooral naar de verschillende fotoformaten (staand, liggend) en hoe we deze het beste in beeld kunnen krijgen. Altijd zoveel mogelijk foto, bijvoorbeeld, onafhankelijk van het formaat en deivce.
