### ISSUE TITLE
Focus van nieuwssite

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#81]
He voor alle nieuws-sitebouwers,

Waar ligt bij jullie de focus van het onderzoek van de afgelopen weken?
Ik ben vooral aan het kijken naar de rangschikking van artikelen bij het schalen van je scherm.

Zoals vorige les laten zien, wil ik op mobiel sommige artikelen naast elkaar plaatsen i.p.v. onder elkaar. Anderen hiermee al gespeeld?

Ook de grote van foto's is iets waar ik mee bezig ben, het lijkt me interessant om hiervoor een testje te doen, hoe belangrijk de foto daadwerkelijk is voor het artikel.

Bij verkiezingscampagne's hoef je niet 10x per dag de kop van Rutte te zien op een nieuwssite, maar willen mensen wel lezen wat hij te zeggen heeft.
Andere hier ideeën over?

**Comment by JanJurre** [comment]
Ik heb mijn focus ook op dit gebied liggen.
Ben ook aan het spelen/expirimenteren met twee artikelen naast elkaar. Ben momenteel aan het uitproberen wat 1 artikel op bijv. 3/5de schermgrootte met foto en de ander op 2/5de schermgrootte zonder foto doet. 
Zodra dit online staat post ik wel ff een linkje.

Wat je zegt over een foto is zeker waar. De ene foto heeft inderdaad meer waarde dan een andere, maar hoe bepaal je dat een foto belangrijk is om te zien?

**Comment by vasilisvg** [comment]
Iets wat je vaak ziet op nieuws-sites is _gerelateerde content_. Bijvoorbeeld linkjes naar meer informatie, meer artikelen van deze auteur, etc. Ik ben ook wel benieuwd naar waar jullie deze content plaatsen op verschillende schermen.
