### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by oledi** [CMDA/mi-mobile-design-forum#82]
Ik had hem al genoemd in de les, maar ik post hem hier nogmaals. Ik wil de plaatjes in mijn dropdown dus netjes naast elkaar hebben. Met een float left/right, gaat het in een raar trap vorm zitten. Heeft iemand hier andere oplossingen voor?
Ik heb ff wat problems met de server, zet hem online zodra het kan. Voor nu: zie plaatje.
overigens, het is momenteel een list.
![untitled](https://cloud.githubusercontent.com/assets/6583281/3152027/4ec84c52-ea89-11e3-8513-529ca4d94b8b.png)

**Comment by Barry91** [comment]
Als de foto's een variabele hoogte hebben kun je alle list items een minimale hoogte (min-height) geven, op deze manier lopen ze gelijk. Ook zou je display: inline-block kunnen proberen op de list items. Of dit oplossingen zijn die jij voor ogen hebt weet ik niet, linkje naar het project zou overigens handig zijn. :)

**Comment by oledi** [comment]
Hier dan eindellijk een linkje: oege.ie.hva.nl/~ranar001/index.html. Het gaat dus over het menuutje rechtsboven als die uitgeklapt is.
