### ISSUE TITLE
<vraag>/<bestel flow>: <het toevoegen en verwijderen van een class op een html element met JS>

### ISSUE THREAD

**Issue by aproskam** [CMDA/mi-mobile-design-forum#83]
Ik probeer momenteel met JS een class toe te voegen of te verwijderen, wanneer je op een knop klikt.

http://aproskam.nl/bestel/index.html

Hij laad momenteel al niet goed in, daar loop ik al vast.

Maar ik zit ook met de vraag, hoe geef ik in het script aan dat wanneer je op knop A klikt, op element A een class "active" komt te staan?

**Comment by bramswier** [comment]
Heb je hier wat aan? Deze kijkt naar de classes van het element, als 'active' er niet aanzit voegt die hem toe. Als je dan nog een keer klikt ('active' zit er dus aan) haalt hij hem weer weg. 

```
document.getElementById('myButton').onclick = function() {

    var className = ' ' + myButton.className + ' ';

    if ( ~className.indexOf(' active ') ) {
        this.className = className.replace(' active ', ' ');
    } else {
        this.className += ' active';
    }              
}
```

http://jsfiddle.net/ttEGY/
http://stackoverflow.com/questions/14615712/toggle-classname-onclick-javascript

**Comment by vasilisvg** [comment]
Er bestaat ook een [`:active` pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:active?redirectlocale=en-US&redirectslug=CSS%2F%3Aactive).

**Comment by joostf** [comment]
Een andere javascript optie is:

<pre>
document.getElementById('myButton').onclick = function() {
     this.classList.toggle('active');
}
</pre>

https://developer.mozilla.org/en-US/docs/Web/API/Element.classList

**Comment by JBostelaar** [comment]
Je kan ook met css het pseudo element :target gebruiken. http://css-tricks.com/on-target/

**Comment by aproskam** [comment]
:target pseudo-class werkt indd het prettigste. Ik ga nog wel een fallback met JS schrijven. Maar het werkt nu wel:

resultaat is te zien bij een mobiele scherm resolutie: 

aproskam.nl/bestel/

**Comment by sjoerdvalk1991** [comment]
Werkt nu prima op mobiel! Wel zou ik consistent zijn in het naar boven of het naar beneden uitklappen nu is het wat verwarrend

**Comment by aproskam** [comment]
Klopt, momenteel verspringt het nog vreemd. Dit komt omdat ik gebruik maak van de :target pseudo-class en deze er voor zorgt dat je naar het id springt dat je opgeeft in de a href waar je naartoe wilt.

Lijkt er op dat de :target pseudo-class toch niet werkt. (tenzij ik met jQuery er voor zorgt dat er niet meer auto. gescrollt wordt). Of iemand een tip/trick?

:active pseudo-class heb ik ook geprobeerd maar krijg dan niet voor elkaar dat het juiste fieldset openblijft staan want zodra je niet meer klikt/drukt op het element waar je de :active pseudo-class aan toegewezen hebt klapt deze meteen weer in.
