### ISSUE TITLE
Vraag / Nieuwssite: Maximum hoogte voor artikel cellen, of juist flexibel?

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#84]
Hey guys,

Ik ben op het moment nog een beetje aan het kloten met m'n layout. Voor mijn gevoel ben ik bijna klaar, echter ben ik nog op een vrij irritante issue gekomen;

www.rizkicalame.com/dfm
(Mijn recente versie staat nog niet online, maar deze URL voldoet ook voor nu)

Bij mijn kopjes Eerder toegevoegd en Recent vandaag maak ik als het ware gebruik van cellen. (Elk artikel zit in een aparte cel). Echter, ben ik er nog niet over uit of ik nou de hoogte van deze cellen van te voren moet vaststellen, of dat ik het dynamisch mee moet laten schalen aan de hand van de lengte van de artikel-titel.

Nadeel van het dynamisch mee laten schalen is dat het er lelijk uit KAN zien, aangezien elke cel dan een andere hoogte kan krijgen. Wat je dan kan krijgen is dat Recent vandaag en Eerder toegevoegd niet even hoog zal zijn, AKA Ugly As F*@#.

Nadeel van het vastzetten van deze hoogte is dat, bij gebrek aan ruimte, lange titels er heel lang uit gaan zien of zelfs eventueel worden ingekort.

Halp, plz. q_q

**Comment by MilanDembinski** [comment]
Ik zou ze toch vast zetten, ik heb even gekeken op http://www.haarlemsdagblad.nl/ en http://www.at5.nl/ waar ze ook met een soort van cellen werken volgens mij en vind dat behoorlijk rommelig ogen. Kun je de positie voor de titels niet zoveel ruimte geven dat ze er, in principe, altijd in passen?

**Comment by rizkicalame** [comment]
Ja dat bedoelde ik inderdaad! Maar het is erg moeilijk te zeggen hoeveel hoogte nou genoeg zal zijn, aangezien titel lengtes erg kunnen varieren. Ik ben een beetje aan het onderzoeken of er best practices zijn voor nieuwssites m.b.t. titellengtes. Als ik wat vind zal ik het wel hier posten. :)

**Comment by MilanDembinski** [comment]
Graag! Moet daar zelf ook nog een oplossing voor verzinnen namelijk. Ik kwam dit artikeltje nog tegen, gaat volgens mij niet perse over titels maar misschien toch handig: http://www.usabilityweb.nl/2006/11/richtlijnen-keurmerk-makkelijk-lezen/
