### ISSUE TITLE
vraag nieuwssite weer/verkeer?

### ISSUE THREAD

**Issue by martijnroosenhart** [CMDA/mi-mobile-design-forum#85]
Ik ben bezig met een nieuwssite en vraag me af of het nut heeft om de verkeersinformatie en de weersvoorspelling te laten zien en op welke plaats (bijvoorbeeld bovenaan in de header of juist op de site zelf)

Heeft iemand anders dit verwerkt in zijn nieuwssite?

**Comment by HiddeStatema** [comment]
Je ziet het wel veel op nieuwswebsites zoals nu.nl en NOS. Maar ik heb nog nooit iemand verder zien klikken of horen zeggen "ja ik wist dat er file stond want stond boven in op nu.nl"

Ik heb er voor gekozen om het niet er in te zetten met de reden omdat ik denk dat het geen toegevoegde waarde heeft.

**Comment by sjoerdvalk1991** [comment]
Ik denk dat je daar inderdaad een keuze in moet maken. Op telegraaf.nl willen ze voorzien in 'alles' dus hebben ze ook een categorie verkeer. Ik laat hem ook achterwege

**Comment by StephanBosma** [comment]
Ik laat het zelf niet zien bij mij gaat het om de content en de verhalen niet om die kleine data
