### ISSUE TITLE
Unveil.js en <noscript> vraag

### ISSUE THREAD

**Issue by casdekker** [CMDA/mi-mobile-design-forum#86]
Ik gebruik Unveil.js om afbeeldingen te lazy loaden. Als img src geef je hierbij een placeholder op die wordt vervangen door de daadwerkelijk afbeelding die in een data-src wordt gedefinieerd.

Als fallback voor wanneer Javascript uitstaat staat er in de documentatie dat er een img tag  met de afbeelding tussen <noscript></noscript> moet worden gezet. De placeholder wordt dan echter ook getoond. 

Is er een manier om er voor te zorgen dat de placeholder niet wordt getoond als Javascript uitgeschakeld staat? 

http://viewlab.nl/portfolio/culinair.html

**Comment by IAmABear** [comment]
Je zou iets zoals <noscript> kunnen gebruiken in je code om daar aan te geven dat er gewoon een plaatje moet staan. Let wel op me <noscript> dat wanneer jij in firefox o.d. zelf javascript uitzet de browser nog steeds denkt dat javascript aanstaat.

Kleine topic er over bij stackoverflow behandeld een beetje waarom het ene oplossing is maar niet de geweldigste:
http://stackoverflow.com/questions/121203/how-to-detect-if-javascript-is-disabled

**Comment by casdekker** [comment]
Thanks!

Ik heb het nu zo gedaan:

Met Unveil.js wordt er in de src een placeholder gedefinieerd, welke vervolgens wordt vervangen door de daadwerkelijke afbeelding wanneer deze is geladen (met behulp van een CSS transitie). Standaard staat die img tag op display: none; en wordt met Javascript op display: block; gezet. Indien er dus geen Javascript is wordt er een placeholder van 280 bytes ingeladen die niet wordt getoond. Die 280 bytes vind ik verwaarloosbaar.
