### ISSUE TITLE
vraag/nieuwssite menubalk over de hele pagina

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#88]
Volgens mij had iemand anders dit probleem al eerder, maar het lukt me niet om men menubalk op groot scherm helemaal te laten doorlopen. Iemand die me hierbij helpen kan?

http://valk-multimedia.com/nieuwssite/versie3/

**Comment by fabianvdwulp** [comment]
In de reset.css file geef je de body een width van 80% mee, dit moet 100% zijn om te zorgen dat de nav over de hele breedte kan lopen. Als je dan deze regel, nav{ background: red; width: 100%; float: left;  } toevoegt, zie je dat de nav nu 100% meeloopt. 

De artikelen staan nu wel verkeerd. Je zal om de artikelen een div moeten zetten die 80% is. Je hebt al om de artikelen een <container> tag staan. Maar deze bestaat volgens mij niet en kan je dus ook niet aanroepen. Ook roep je de <nav> in de css aan met .nav{}. Dit zou nav{ } moeten zijn. Goed om hier even op te letten. Hopelijk helpt dit je.
