### ISSUE TITLE
Vraag centreren css

### ISSUE THREAD

**Issue by MartijnEngelkes** [CMDA/mi-mobile-design-forum#89]
Hey mensen,

Even een vraagje. Ik ben redelijk onhandig met css positioneren en centreren. Weet iemand hoe ik die thumpnails onderaan goed in het midden kan krijgen? Heb al geprobeerd met margin: auto; maar er komt niets in het midden.

![schermafbeelding 2014-06-05 om 16 50 41](https://cloud.githubusercontent.com/assets/7351989/3189202/6eec6eac-ecc1-11e3-9184-854067163ce7.png)

Dit is de code in CSS:

.other {
    height: 20%;
    width: 100%;
    text-align:center;
    color:#FFF;
    margin-top:1%;
    margin-left: auto;
        margin-right:auto;

}

div.img
{

```
padding: 5px;
border: 1px solid #FFFFFF;
height: auto;
width: auto;
float: left;
text-align: center;
margin-left: 1%;
```

}

**Comment by TDMW** [comment]
Probeer eens in plaats van margin-left en margin-right alleen 'margin: 0 auto;'.

**Comment by arjentnkmp** [comment]
Heb je om de thumbnails in z'n geheel een div staan, die je margin-left/right:auto; geeft? En heb je ook de juiste clear:both, op die div toegepast?

**Comment by Barry91** [comment]
Link naar je project zou wederom handig zijn. Zorg ervoor dat de foto items zich in een container bevinden en geef de container de waarde "margin: 0 auto".

**Comment by MartijnEngelkes** [comment]
Helaas heb ik even geen webruimte, vandaar dat het niet online staat. Alle thumpnails staan in een div class en die staan weer in de div class: other. Ik heb margin: 0 auto geprobeerd en margin-left/right:auto. Ik heb ook clear:both toegevoegd. Het doet nu ongeveer wat ik wil dus bedankt allemaal daarvoor! Enige wat nog niet precies doet wat ik wil is de smalle modus: De thumpnails moeten daar ook in het midden eigenlijk. Snap niet helemaal waarom ze daar dan aan de linkerzijde blijven staan.

![schermafbeelding 2014-06-10 om 12 51 18](https://cloud.githubusercontent.com/assets/7351989/3228921/3ebfe2b6-f08d-11e3-8241-77a882dc8e84.png)

**Comment by IAmABear** [comment]
Martijn ik zal morgen tijdens de les wel tijdelijke webruimte voor je beschikbaar maken zodat je dit soort dingen kan share + overall kan testen
