### ISSUE TITLE
Flex-wrap Firefox probleem

### ISSUE THREAD

**Issue by TDMW** [CMDA/mi-mobile-design-forum#90]
Zijn er meer mensen die problemen hebben met flexbox (flex-wrap) in Firefox? Ik heb hier nog geen work around voor gevonden. In safari verspringt mijn margin een beetje, in chrome werkt alles perfect. In Firefox wrapped hij mn complete flex items niet waardoor ik alles op 1 lijn krijg in plaats van 3 columns netjes onder elkaar. 

Dit is momenteel mijn div met flex in css:

```
.flex-container {
  padding: 0;
  margin: 0;
  list-style: none;

  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  flex-wrap: wrap;

  -webkit-flex-flow: row wrap;
  justify-content: space-around;
}
```

**Comment by rappel93** [comment]
Ik heb hetzelfde probleem. Zelfde code en helaas nog niks hierop gevonden.

**Comment by casdekker** [comment]
Ik zie toevallig net dat dit ook het geval is met Safari op een iPad 1.
