### ISSUE TITLE
Vraag/nieuwssite /Wie heeft er goede suggesties voor een smaller font dan dat ik nu gebruik.

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#91]

**Comment by sjoerdvalk1991** [comment]
http://valk-multimedia.com/nieuwssite/versie5/

**Comment by HiddeStatema** [comment]
Wat ik altijd een fijn font vind is Open sans. gratis te gebruiken van Google Fonts.
http://www.google.com/fonts/specimen/Open+Sans

Wat je ook nog kan doen is de letterspacing minder zetten, dan komen de letters ook dichter op elkaar. Let wel dat het niet te dicht op elkaar staat dat het weer niet leesbaar is voor mensen met dyslexie..

**Comment by casdekker** [comment]
Voor headlines vind ik Pragmatica wel nice, kijk anders eens bij de fonts van Adobe Typekit https://typekit.com/lists/condensed-headline-fonts

**Comment by bramswier** [comment]
Lato vind ik zelf ook wel fijn. Is ook in verschillende letterdiktes.

https://www.google.com/fonts#UsePlace:use/Collection:Lato
