### ISSUE TITLE
Leesonderzoek

### ISSUE THREAD

**Issue by HiddeStatema** [CMDA/mi-mobile-design-forum#92]
Ik ben voor m'n nieuwssite een onderzoekje aan het doen hoe snel mensen gemiddeld kunnen lezen. Ik heb al verschillende resultaten van familie en vrienden, maar zou ook graag jullie er bij betrekken. 

Zouden jullie met je smartphone bij willen houden hoe lang je doet om onderstaand artikel te lezen? Dat graag hier posten :)
Iedereen die het leest en post ben ik eeuwig dankbaar 😘

http://mobiel.nu.nl/ondernemen/3796501/dubieuze-rol-nederlandse-bedrijven-in-qatar.html

**Comment by IAmABear** [comment]
Voor mensen die de url te lang vinden om in te tikken:
http://tinyurl.com/hiddesarticle

Ik deed er overigens iets meer als een minuut over om het artikel te lezen
