### ISSUE TITLE
Vraag / Nieuwssite: Gradients bij IEDEREEN, of alleen voor Progressive Enhancement?

### ISSUE THREAD

**Issue by rizkicalame** [CMDA/mi-mobile-design-forum#94]
Hey guys,

Vorige week heb ik mijn nieuwspagina gepresenteerd, waarbij jullie konden zien dat ik gradients in mijn artikelpagina heb toegepast om de leesbaarheid van het artikel te bevorderen. Deze gradients vallen volledig in 1 lijn met het Progressive Enhancement-principe, waarbij ik eerst kijk of de browser van de gebruiker CSS3 gradients ondersteunt, zo ja; dan voeg ik de gradients toe. Echter, ben ik aan het denken geweest, en heb ik gedacht: 

"Waarom maak ik niet gewoon .png's van die gradients, zodat iedereen van de voordelen van de gradients kan genieten?"

Wat denken jullie? De progressive enhancement manier, of de png's?

**Comment by aproskam** [comment]
De groote van png's zal waarschijnlijk miniem zijn, helemaal wanneer je deze nog compressed(mocht dit uberhaupt werken op zo'n afbeelding)

**Comment by casdekker** [comment]
Waarom een PNG en geen JPEG?

**Comment by rizkicalame** [comment]
Omdat JPEG niks met transparantie kan, oftewel geen gradients. :-)

**Comment by casdekker** [comment]
Een gradient is niks meer dan een kleurverloop, dus als je m laat verlopen van kleur naar kleur heb je geen transparantie nodig en dus ook geen PNG. Een transparantie laag toevoegen zorgt er sowieso voor dat je bestand groter wordt.

Is de gradient voor op de achtergrond? Ik zou hem in dat geval niet te klein maken, als je upscaled worden gradients altijd onwijs lelijk/streperig. Zelf heb ik goede ervaringen met het upscalen van gradients met noise.

**Comment by bramswier** [comment]
Je kan bijvoorbeeld eerst een kleur doen voor alle browsers (fallback). Die overrule je met een gradient in de vorm van een plaatje voor iedere browser. Als de browser cssgradients ondersteunt, dan overrule je dat plaatje in de .cssgradients-class met een CSS-gradient.

**Comment by Barry91** [comment]
Zelf gebruik ik deze tool: http://www.colorzilla.com/gradient-editor/ om gradients te genereren, erg handig en met een fallback voor oudere browsers. Haakt ook in op wat Bram zegt.
