### ISSUE TITLE
Flexbox centreren

### ISSUE THREAD

**Issue by MilanDembinski** [CMDA/mi-mobile-design-forum#95]
Ik heb een vraag: Ik maak nu gebruik van flexbox en in Chrome centreert hij de blokjes, in Safari doet ie dat niet, daar schuift alles naar links. Iemand een idee hoe dat op te lossen is of waar het aan ligt?

**Comment by TVoorend** [comment]
Kan je link sturen van je project?

**Comment by martijnroosenhart** [comment]
Heb je webkit gebruikt?

**Comment by JBostelaar** [comment]
Maak je ook goed gebruik van de prefixes? -webkit- etc.?
