### ISSUE TITLE
Vraag | Background-cover

### ISSUE THREAD

**Issue by rappel93** [CMDA/mi-mobile-design-forum#97]
Hallo iedereen,

Ik heb een vraag over de css optie Background-cover.

Hoe zit het met de support binnen alle browsers? Is deze optie al overal te gebruiken. En als dit niet het geval is, zijn er mogelijkheden om dit wel voor elkaar te krijgen?

**Comment by fabianvdwulp** [comment]
Je kan hier even checken welke browsers het supporten: http://caniuse.com/#feat=background-img-opts

Mocht je een andere manier zoeken om het te fixen. Ik vind de fullscreenr plugin met jquery heel goed werken. https://gist.github.com/chrisvanpatten/1511820
