### ISSUE TITLE
<bevinding>/<algemeen> onclick jquery functie niet werkt op firefox os.

### ISSUE THREAD

**Issue by sjoerdvalk1991** [CMDA/mi-mobile-design-forum#98]
Tijdens het testen bij Frontlab kwam ik er achter dat mijn menu niet uitklapt op een bepaalde versie van firefox os. Dit komt omdat de onclick niet herkent wordt door die browser. Hiervoor zou ik nog een andere microlibrary kunnen inladen zoals quo.js, maar is er misschien een betere manier?

**Comment by Barry91** [comment]
Welke jQuery code gebruik je om het click event af te vangen?

**Comment by aproskam** [comment]
Hoe belangrijk is dit inklap menu?
En tot in hoever wil je dit supporten? Nog een library betekent nog meer laadtijd?
